# Generated by Django 5.1.5 on 2025-02-14 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper&cardboard', 'Paper&cardboard'), ('glass', 'Glass'), ('organic', 'Organic'), ('electronic', 'Electronic'), ('hazardous', 'Hazardous')], max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('prefer not to say', 'prefer not to say')], default='select', max_length=50, null=True)),
                ('DOB', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('cv', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('Username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('Confirm_Password', models.CharField(max_length=20)),
                ('licenses', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='our_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('prefer not to say', 'prefer not to say')], default='select', max_length=50, null=True)),
                ('DOB', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('cv', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('Username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('Confirm_Password', models.CharField(max_length=20)),
                ('licenses', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField()),
                ('Address', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=50)),
                ('Confirm_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('so_fname', models.CharField(max_length=20)),
                ('so_lname', models.CharField(max_length=20)),
                ('so_email', models.EmailField(max_length=254)),
                ('so_phone', models.IntegerField()),
                ('so_address', models.TextField()),
                ('so_district', models.CharField(max_length=20)),
                ('so_city', models.CharField(max_length=20)),
                ('so_pincode', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150)),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_id', models.CharField(max_length=150, null=True)),
                ('order_id', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Waste', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.add_waste')),
                ('Worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.our_employee')),
                ('User_details', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.reg')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('replydate', models.CharField(max_length=100)),
                ('complaintdate', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.reg')),
            ],
        ),
    ]
