# Generated by Django 5.1.5 on 2025-02-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity2',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('pick up confirm', 'pick up confirm'), ('collected', 'collected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150),
        ),
    ]
