# Generated by Django 5.1.5 on 2025-02-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='Email',
            field=models.CharField(max_length=120),
        ),
    ]
