# Generated by Django 5.1.5 on 2025-02-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='our_employee',
            name='Email',
            field=models.CharField(max_length=220),
        ),
    ]
